version: 0.2

phases:
  build:
    commands:
      - mvn clean package
    post_builds:
      - echo Build completed successfully
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes